### ISSUE TITLE
dup_key error after manually deleting is-master collection in MongoDB

### ISSUE THREAD

**Issue by jmsaavedra** [mattpker/node-is-master#11]
after about 20 minutes or so of the app running ( cluster of 4 via pm2 ), i am getting this error:

```
{ [MongoError: E11000 duplicate key error index: my_db.forks.$startDate_1 dup key: { : null }]
name: 'MongoError',
message: 'E11000 duplicate key error index: my_db.forks.$startDate_1 dup key: { : null }',
driver: true,
index: 0,
code: 11000,
errmsg: 'E11000 duplicate key error index: my_db.forks.$startDate_1 dup key: { : null }' }
```

running pm2 v0.15.10 on node v5.0.0 on a linux ec2 box

any ideas?

**Comment by mattpker** [comment]
Are you running the latest version of is-master? An issue similar to this was fixed in v1.1.4.

**Comment by mattpker** [comment]
Also, based on the error that you provided, the duplicate key is in the startDate with the value of 'null'. Reviewing the code, the only way that it appears that could happen is if you manually deleted the values from mongo. Is it possible that you did this?

**Comment by mattpker** [comment]
@bendalton When you pushed https://github.com/mattpker/node-is-master/commit/1441d581648d2745e54ea98105d67f39c96f7af6 did you test the upsert functionality? Because looking at it now, I don't think it would get a startDate thus being set to 'null' and causing dup key errors. Im thinking that this might be @jmsaavedra issue.

**Comment by jmsaavedra** [comment]
@mattpker indeed, I deleted the `forks` collection, in order to re-initialize the master fork. I set the `timeout` to something low like 30, but even then was waiting minutes for `im.on('master',` to hit, over app restarts. So that explains that!

more info: I was using this package in conjunction with pm2's clustering, and needed a few processes to be run by just one fork.  I did get is-master working, but in the end I found the `process.env.NODE_APP_INSTANCE` var and have made that work for my needs. 

Thanks for looking into this!  I'll let you close the issue (assuming it's not any upsert failure) --

**Comment by mattpker** [comment]
@jmsaavedra, thanks for the feedback. Yeah this is an issue that needs to be fixed with upserts so that we can keep running in case of the collection or record being manually deleted. I will keep working with @bendalton on a solution for this.

As for the 30 second timeout part, I have a FAQ in the readme that addresses this exact situation. In the code I manually add 60 seconds to any timeout so that someone does not set it to low. So the fastest the timeout can ever be is 1 minute. 

A warning for using `process.env.NODE_APP_INSTANCE`, I am assuming that you are using id 0 = master. This can be a problem because if id 0 crashes, then there is no longer a master process. This is one of the reason I created is-master before I even started clustering on multiple servers.

Let me know if you have any questions.
