### ISSUE TITLE
mongodb document expiry only runs every minute or so

### ISSUE THREAD

**Issue by em0ney** [mattpker/node-is-master#14]
Hi @mattpker ,

Thought you should include somewhere on your readme, some information to explain that mongodb's document expiry only runs every minute or so.  As a result, if the master dies, it can take a minute or so for a new master to be promoted.  Even longer if based on the default expiry/timeout settings (which I have PR'd to improve hopefully)

I understand this is just a caveat of the approach being used - but it is really important to communicate these so people know before spending too much time investigating for themselves.

Thanks for writing this cool module 👍

**Comment by mattpker** [comment]
This is already explained in the README's FAQ that 60 seconds is added to the expire, so it should already be assumed that at a minimum it should take at least a minute for a slave to be promoted to master when the master dies. I have this hardcoded and explained this way in the FAQ so that the users can understand that this implementation will only go as fast as about 1 to 2 minutes on promoting slaves to masters. Something else would need to be written if you needed something faster.
